import test from 'node:test';
import assert from 'node:assert/strict';
import { CallObserver } from '../dist/call-observation.js';
const target = {name:'test',label:'Test',host:'127.0.0.1',port:5038};
class Transport {
  events = new Set(); lifecycle = new Set(); rows = []; actions = []; hook;
  subscribeEvents(f) {this.events.add(f);return ()=>this.events.delete(f);}
  subscribeLifecycle(f) {this.lifecycle.add(f);return ()=>this.lifecycle.delete(f);}
  emit(Event,id,extra={}) {for(const f of this.events) f({Event,Uniqueid:id,Channel:`PJSIP/${id}`,Exten:'100',Context:'mcp-test',...extra});}
  close(){for(const f of this.lifecycle)f('explicit_close');}
  async action(a,_timeout,o={}) {this.actions.push(a);if(this.hook){const r=await this.hook(a,o);if(r)return r;}
    if(a.Action==='Events')return [{Response:'Success'}];
    if(a.Action==='CoreShowChannels')return [{Response:'Success'},...this.rows.map(r=>({Event:'CoreShowChannel',...r})),{Event:'CoreShowChannelsComplete'}];
    return [{Response:'Error',Message:'No such variable'}];}
}
function setup(timeout=100){const ami=new Transport();const observer=new CallObserver(target,()=>async()=>ami,timeout);return {ami,observer};}
const deadline=(ms=100)=>performance.now()+ms;
test('bootstrap lifecycle wins over stale baseline and retains original DID',async()=>{
 const {ami,observer}=setup();ami.rows=[{Channel:'PJSIP/a',Uniqueid:'a',Exten:'changed',Context:'later'}];
 ami.hook=async a=>{if(a.Action==='Events'){ami.emit('Newchannel','a');ami.emit('Newstate','a',{ChannelStateDesc:'Up'});ami.emit('Hangup','a',{Cause:'16','Cause-txt':'Normal Clearing'});}};
 const ready=await observer.ensureReady();const result=await observer.recentCalls({},deadline());assert.equal(result.records.length,1);const r=result.records[0];assert.equal(r.originalExtension,'100');assert.equal(r.answered,'yes');assert.equal(r.endState,'hangup');assert.equal(r.startCoverage,'newchannel');assert.ok(r.duration>=0);assert.equal(ready.generation,1);observer.close();
});
test('fast call with since completes; no-since excludes preexisting terminal',async()=>{const {ami,observer}=setup();const ready=await observer.ensureReady();ami.emit('Newchannel','a');ami.emit('Hangup','a');const r=await observer.waitCall({did:'100',since:ready.observationSince},deadline());assert.equal(r.outcome,'completed');assert.equal(r.record.answered,'no');const n=await observer.waitCall({did:'100'},deadline(5));assert.equal(n.outcome,'timed_out_no_match');observer.close();});
test('baseline Up and orphan are partial and do not DID match',async()=>{const {ami,observer}=setup();ami.rows=[{Uniqueid:'a',Channel:'PJSIP/a',Exten:'100',ChannelStateDesc:'Up'}];await observer.ensureReady();ami.emit('Hangup','a');ami.emit('Hangup','b');const {records}=await observer.recentCalls({},deadline());assert.equal(records[1].answered,'yes');assert.equal(records[1].observedStartedAt,null);assert.equal(records[0].answered,'unknown');assert.equal(records[0].duration,null);const r=await observer.waitCall({did:'100',since:new Date(Date.now()-100).toISOString()},deadline());assert.equal(r.outcome,'observation_gap');observer.close();});
test('gap ends active legs without completing them and later invocation reconnects',async()=>{const {ami,observer}=setup();await observer.ensureReady();const waiting=observer.waitCall({did:'100'},deadline());await Promise.resolve();ami.emit('Newchannel','a');ami.close();assert.equal((await waiting).outcome,'observation_gap');const r=await observer.recentCalls({},deadline());assert.equal(r.records[0].endState,'unknown');assert.equal(r.records[0].hangupCause,null);assert.equal(r.coverage.generation,2);observer.close();});
const tick=()=>new Promise(r=>setImmediate(r));
const paused=(signal)=>new Promise((_,reject)=>{if(signal.aborted)reject(new Error('cancelled'));else signal.addEventListener('abort',()=>reject(new Error('cancelled')),{once:true});});
test('duplicate lifecycle is idempotent and ending Linkedid sibling does not finish other leg',async()=>{const {ami,observer}=setup();await observer.ensureReady();ami.emit('Newchannel','a',{Linkedid:'L',Exten:'100'});ami.emit('Newchannel','a');ami.emit('Newchannel','b',{Linkedid:'L',Exten:'200'});const wait=observer.waitCall({did:'200'},deadline(8));await tick();ami.emit('Hangup','a');ami.emit('Hangup','a');assert.equal((await wait).outcome,'timed_out_active');const r=await observer.recentCalls({},deadline());assert.equal(r.records.length,1);observer.close();});
test('refused Events and incomplete bootstrap never publish ready; next attempt is fresh',async()=>{
 for(const mode of ['refused','incomplete','timeout']){const {ami,observer}=setup(12);ami.hook=async(a,o)=>{if(a.Action==='Events'&&mode==='refused')return [{Response:'Error',Message:'Permission denied'}];if(a.Action==='Events'&&mode==='timeout')return paused(o.signal);if(a.Action==='CoreShowChannels'&&mode==='incomplete')return [{Response:'Success'}];};await assert.rejects(observer.ensureReady());assert.equal(observer.coverage().ready,false);assert.equal(ami.events.size,0);ami.hook=undefined;assert.equal((await observer.ensureReady()).generation,2);observer.close();}
});
test('129 live legs and combined 512 bootstrap entries invalidate generation',async()=>{
 const a=setup();await a.observer.ensureReady();for(let i=0;i<129;i++)a.ami.emit('Newchannel',String(i));assert.equal(a.observer.coverage().ready,false);assert.equal(a.observer.coverage().gaps.at(-1).reason,'live_capacity');const r=await a.observer.recentCalls({limit:100},deadline());assert.equal(r.records.length,100);assert.ok(r.records.every(r=>r.endState==='unknown'));a.observer.close();
 const b=setup(20);b.ami.hook=async(req,o)=>{if(req.Action==='Events'){for(let i=0;i<256;i++)b.ami.emit('Hangup',String(i));return paused(o.signal);}};await assert.rejects(b.observer.ensureReady());assert.equal(b.observer.coverage().gaps.some(g=>g.reason==='bootstrap_capacity'),true);assert.equal(b.ami.events.size,0);b.observer.close();
});
test('terminal ring eviction ends no-since waiter with unknown pending identity and competing matches',async()=>{
 const {ami,observer}=setup(1000);await observer.ensureReady();ami.hook=async(a,o)=>a.Action==='Getvar'?paused(o.signal):undefined;
 ami.emit('Newchannel','pending');const wait=observer.waitCall({callId:'wanted'},deadline(1000));await tick();ami.emit('Hangup','pending');
 for(let i=0;i<257;i++){ami.emit('Newchannel',`r${i}`);ami.emit('Hangup',`r${i}`);}
 assert.equal((await wait).outcome,'observation_gap');assert.equal(observer.coverage().evictedCount,2);const r=await observer.recentCalls({limit:2},deadline());assert.deepEqual(r.records.map(r=>r.uniqueid),['r256','r255']);observer.close();
 const other=setup();await other.observer.ensureReady();other.ami.emit('Newchannel','competing');const waiting=other.observer.waitCall({did:'100'},deadline(1000));await tick();other.ami.emit('Hangup','competing');for(let i=0;i<257;i++){other.ami.emit('Newchannel',`other${i}`,{Exten:'200'});other.ami.emit('Hangup',`other${i}`);}assert.equal((await waiting).outcome,'observation_gap');other.observer.close();
});
test('16 waiter limit; cancellation frees own slot and shared ready state',async()=>{const {ami,observer}=setup();await observer.ensureReady();const controller=new AbortController();const waits=Array.from({length:16},(_,i)=>observer.waitCall({did:String(i)},deadline(50),i===0?controller.signal:undefined));const cancelled=assert.rejects(waits[0],/cancelled/);await assert.rejects(observer.waitCall({did:'overflow'},deadline()),/capacity/);controller.abort();await cancelled;assert.equal(observer.coverage().ready,true);const replacement=observer.waitCall({did:'replacement'},deadline(1));assert.equal((await replacement).outcome,'timed_out_no_match');observer.close();await Promise.all(waits.slice(1));});
test('gap interval ring advances horizon while older record survives',async()=>{const {ami,observer}=setup();const ready=await observer.ensureReady();ami.emit('Newchannel','old');ami.emit('Hangup','old');for(let i=0;i<130;i++){ami.close();await observer.ensureReady();}const coverage=observer.coverage();assert.equal(coverage.gaps.length,256);assert.ok(coverage.droppedGapCount>0);const r=await observer.recentCalls({since:ready.observationSince},deadline());assert.equal(r.records[0].uniqueid,'old');assert.equal(r.coverage.requestedRangeComplete,false);assert.equal((await observer.waitCall({did:'100',since:ready.observationSince},deadline())).outcome,'observation_gap');observer.close();});
test('short caller deadline does not cancel shared startup; close prevents late readiness',async()=>{let release;const transport=new Transport();let attempts=0;const observer=new CallObserver(target,(_end,signal)=>{attempts++;return ()=>new Promise((resolve,reject)=>{release=()=>resolve(transport);signal.addEventListener('abort',()=>reject(new Error('cancelled')),{once:true});});},100);
 const short=observer.waitCall({did:'x'},deadline(5));const long=observer.waitCall({did:'x'},deadline(100));assert.equal((await short).outcome,'observation_gap');release();await tick();assert.equal(attempts,1);assert.equal(observer.coverage().ready,true);observer.close();assert.equal((await long).outcome,'observation_gap');await assert.rejects(observer.ensureReady(),/closed/);
 let late;const other=new CallObserver(target,()=>()=>new Promise(r=>{late=r;}),100);const p=other.ensureReady();other.close();late(transport);await assert.rejects(p);assert.equal(other.coverage().ready,false);assert.equal(transport.actions.filter(a=>a.Action==='Events').length,1);
});
test('Getvar concurrency stays at eight and exact Call-ID ambiguity waits for pending metadata',async()=>{
 const {ami,observer}=setup(200);await observer.ensureReady();let inFlight=0,max=0;const releases=[];
 ami.hook=async(a,o)=>{if(a.Action!=='Getvar')return;inFlight++;max=Math.max(max,inFlight);try{if(a.Variable==='CHANNEL(uniqueid)'){await new Promise((resolve,reject)=>{releases.push(resolve);o.signal.addEventListener('abort',()=>reject(new Error('cancelled')),{once:true});});return [{Response:'Success',Value:a.Channel.slice(6)}];}return [{Response:'Success',Value:a.Variable==='CHANNEL(pjsip,call-id)'?'wanted':''}];}finally{inFlight--;}};
 for(let i=0;i<12;i++)ami.emit('Newchannel',String(i));await tick();assert.equal(max,8);assert.equal(inFlight,8);observer.close();await tick();assert.equal(inFlight,0);assert.equal(ami.events.size,0);
 const second=setup(100);await second.observer.ensureReady();let secondRelease;second.ami.hook=async(a,o)=>{if(a.Action!=='Getvar')return;if(a.Channel==='PJSIP/b'&&a.Variable==='CHANNEL(uniqueid)'&&!secondRelease){await new Promise(resolve=>secondRelease=resolve);}return [{Response:'Success',Value:a.Variable==='CHANNEL(uniqueid)'?a.Channel.slice(6):a.Variable==='CHANNEL(pjsip,call-id)'?'wanted':''}];};
 second.ami.emit('Newchannel','a');await tick();second.ami.emit('Newchannel','b');const result=second.observer.waitCall({callId:'wanted'},deadline(100));await tick();second.ami.emit('Hangup','a');let settled=false;result.then(()=>settled=true);await tick();assert.equal(settled,false);secondRelease();assert.equal((await result).outcome,'ambiguous_match');second.observer.close();
});
test('unavailable metadata at deadline exposes uncertainty rather than absence',async()=>{const {ami,observer}=setup();await observer.ensureReady();ami.emit('Newchannel','a');const r=await observer.waitCall({callId:'missing'},deadline(5));assert.equal(r.outcome,'timed_out_no_match');assert.equal(r.coverage.correlationComplete,false);assert.ok(r.coverage.correlationReasons.includes('not_observed'));observer.close();});
test('startup expiration aborts holder including retry; later call receives fresh holder',async()=>{const transport=new Transport();let calls=0;let aborted=false;const observer=new CallObserver(target,(end,signal)=>{calls++;if(calls===1)return async()=>{await new Promise((_,reject)=>signal.addEventListener('abort',()=>{aborted=true;reject(new Error('cancelled'));},{once:true}));};return async()=>transport;},8);await assert.rejects(observer.ensureReady(),/timed out/);assert.equal(aborted,true);assert.equal((await observer.ensureReady()).generation,2);assert.equal(calls,2);observer.close();});
test('ready no-since waiter arms synchronously before an immediate fast call',async()=>{const {ami,observer}=setup();await observer.ensureReady();const waiting=observer.waitCall({did:'100'},deadline());ami.emit('Newchannel','now');ami.emit('Hangup','now');assert.equal((await waiting).outcome,'completed');observer.close();});
test('since additionally includes active partial leg and reports unknown DID identity',async()=>{const {ami,observer}=setup();ami.rows=[{Uniqueid:'a',Channel:'PJSIP/a',Exten:'100'}];const ready=await observer.ensureReady();const r=await observer.waitCall({did:'100',since:ready.observationSince},deadline(2));assert.equal(r.outcome,'timed_out_no_match');assert.equal(r.coverage.correlationComplete,false);observer.close();});
import { AmiClient } from '../dist/ami.js';
import { startMockAmi } from './helpers/mock-ami.mjs';
import { once } from 'node:events';
const closedSockets = mock => Promise.all([...mock.sockets].map(s => once(s,'close',{signal:AbortSignal.timeout(200)})));
async function wire(t,timeout=200){const mock=await startMockAmi();let factories=0;const observer=new CallObserver(target,(end,signal)=>{factories++;let client;signal.addEventListener('abort',()=>client?.close(),{once:true});return async()=>{client=new AmiClient({host:'127.0.0.1',port:mock.port,username:'mcp',password:'secret',timeoutMs:Math.max(1,end-performance.now())});await client.connect();return client;};},timeout);t.after(async()=>{observer.close();await mock.close();});return {mock,observer,factories:()=>factories};}
test('wire subscription installs listener before acknowledgement and list merge retains terminal',async t=>{const {mock,observer}=await wire(t);mock.channels=[{Uniqueid:'a',Channel:'PJSIP/a',Exten:'wrong'}];mock.eventsBeforeReply.Events=[{Event:'Newchannel',Uniqueid:'a',Channel:'PJSIP/a',Exten:'100',Context:'mcp-test'},{Event:'Newstate',Uniqueid:'a',Channel:'PJSIP/a',ChannelStateDesc:'Up'},{Event:'Hangup',Uniqueid:'a',Channel:'PJSIP/a'}];await observer.ensureReady();const r=await observer.recentCalls({},deadline());assert.equal(r.records.length,1);assert.equal(r.records[0].originalExtension,'100');assert.equal(r.records[0].answered,'yes');assert.equal(mock.actions('Events')[0].EventMask,'call');});
test('wire bootstrap 129th non-PJSIP row closes socket immediately without Complete',async t=>{const {mock,observer}=await wire(t);mock.channels=Array.from({length:129},(_,i)=>({Uniqueid:String(i),Channel:`Local/${i}`}));mock.omitComplete=true;await assert.rejects(observer.ensureReady(),/maxRows/);await closedSockets(mock);assert.equal(observer.coverage().ready,false);assert.equal(mock.sockets.size,0);});
test('wire login plus Events plus bootstrap share original startup budget',async t=>{const {mock,observer,factories}=await wire(t,35);mock.loginDelayMs=20;mock.actionDelayMs.CoreShowChannels=60;await assert.rejects(observer.ensureReady(),/timed out|expired|incomplete/i);await closedSockets(mock);assert.equal(mock.sockets.size,0);mock.loginDelayMs=0;mock.actionDelayMs.CoreShowChannels=0;assert.equal((await observer.ensureReady()).generation,2);assert.equal(factories(),2);});
test('dialplan movement preserves exact original DID/context and ambiguity includes simultaneous legs',async()=>{const {ami,observer}=setup();await observer.ensureReady();ami.emit('Newchannel','a');ami.emit('Newstate','a',{Exten:'other',Context:'later',ChannelStateDesc:'Up'});const w=observer.waitCall({did:'100',context:'mcp-test'},deadline());ami.emit('Newchannel','b');assert.equal((await w).outcome,'ambiguous_match');ami.emit('Hangup','a');const {records}=await observer.recentCalls({},deadline());assert.equal(records[0].originalContext,'mcp-test');assert.equal(records[0].originalExtension,'100');observer.close();});
test('late old enrichment cannot publish across gap into reused Uniqueid/channel',async()=>{const {ami,observer}=setup();await observer.ensureReady();let release;ami.hook=async a=>{if(a.Action==='Getvar'&&a.Variable==='CHANNEL(uniqueid)'&&!release)await new Promise(r=>release=r);return a.Action==='Getvar'?[{Response:'Success',Value:a.Variable==='CHANNEL(uniqueid)'?'a':'old-id'}]:undefined;};ami.emit('Newchannel','a');await tick();ami.close();ami.hook=undefined;await observer.ensureReady();ami.emit('Newchannel','a');release();await tick();ami.emit('Hangup','a');const {records}=await observer.recentCalls({},deadline());assert.equal(records[0].generation,2);assert.equal(records[0].fullCallId,null);assert.equal(records[1].generation,1);assert.equal(records[1].sipMetadata.fields.fullCallId.reason,'observation_gap');observer.close();});

test('filtered recent coverage includes unresolved terminal Call-ID before filtering and limit',async t=>{
 const {ami,observer}=setup();t.after(()=>observer.close());await observer.ensureReady();
 const empty=await observer.recentCalls({callId:'wanted'},deadline());assert.equal(empty.coverage.correlationComplete,true);
 ami.emit('Newchannel','unknown');ami.emit('Hangup','unknown');
 const unknown=await observer.recentCalls({callId:'wanted'},deadline());assert.deepEqual(unknown.records,[]);assert.equal(unknown.coverage.correlationComplete,false);assert.deepEqual(unknown.coverage.correlationReasons,['channel_gone']);
 ami.hook=async a=>a.Action==='Getvar'?[{Response:'Success',Value:a.Variable==='CHANNEL(uniqueid)'?a.Channel.slice(6):a.Variable==='CHANNEL(pjsip,call-id)'?'wanted':''}]:undefined;
 ami.emit('Newchannel','known');await tick();ami.emit('Hangup','known');
 const mixed=await observer.recentCalls({callId:'wanted',limit:1},deadline());assert.deepEqual(mixed.records.map(r=>r.uniqueid),['known']);assert.equal(mixed.coverage.correlationComplete,false);assert.deepEqual(mixed.coverage.correlationReasons,['channel_gone']);
 const all=await observer.recentCalls({},deadline());assert.equal(all.coverage.correlationComplete,true);assert.deepEqual(all.coverage.correlationReasons,[]);
 await new Promise(r=>setTimeout(r,2));const since=new Date().toISOString();ami.emit('Newchannel','later');await tick();ami.emit('Hangup','later');
 const recent=await observer.recentCalls({callId:'wanted',since},deadline());assert.deepEqual(recent.records.map(r=>r.uniqueid),['later']);assert.equal(recent.coverage.correlationComplete,true);
});

test('missing original DID or requested context remains uncertain for wait and recent',async t=>{
 for(const [extra,selector] of [[{Exten:undefined},{did:'100'}],[{Context:undefined},{did:'100',context:'mcp-test'}]]){
  const {ami,observer}=setup();t.after(()=>observer.close());await observer.ensureReady();const wait=observer.waitCall(selector,deadline(10));
  ami.emit('Newchannel','partial',extra);ami.emit('Newstate','partial',{Exten:'100',Context:'mcp-test'});ami.emit('Hangup','partial');
  const result=await wait;assert.equal(result.outcome,'timed_out_no_match');assert.equal(result.coverage.correlationComplete,false);assert.deepEqual(result.coverage.correlationReasons,['not_observed']);
  const recent=await observer.recentCalls(selector,deadline());assert.deepEqual(recent.records,[]);assert.equal(recent.coverage.correlationComplete,false);assert.deepEqual(recent.coverage.correlationReasons,['not_observed']);
  const all=await observer.recentCalls({},deadline());assert.equal(all.records[0].startCoverage,'newchannel');assert.equal(all.records[0].originalExtensionObserved,true);assert.equal(all.coverage.correlationComplete,true);
  if('Context' in extra){const did=await observer.recentCalls({did:'100'},deadline());assert.equal(did.records.length,1);assert.equal(did.coverage.correlationComplete,true);}
 }
});

test('partial baseline and orphan terminal DID identity is uncertain in recent results',async t=>{
 const {ami,observer}=setup();t.after(()=>observer.close());ami.rows=[{Uniqueid:'baseline',Channel:'PJSIP/baseline',Exten:'100',Context:'mcp-test'}];await observer.ensureReady();ami.emit('Hangup','baseline');ami.emit('Hangup','orphan');
 const recent=await observer.recentCalls({did:'100'},deadline());assert.deepEqual(recent.records,[]);assert.equal(recent.coverage.correlationComplete,false);assert.deepEqual(recent.coverage.correlationReasons,['not_observed']);
});

test('pending Call-ID wait coverage stays distinct from terminal recent coverage',async t=>{
 const {ami,observer}=setup();t.after(()=>observer.close());await observer.ensureReady();ami.hook=async(a,o)=>a.Action==='Getvar'?paused(o.signal):undefined;
 ami.emit('Newchannel','pending');const wait=await observer.waitCall({callId:'wanted'},deadline(5));assert.equal(wait.outcome,'timed_out_no_match');assert.equal(wait.coverage.correlationComplete,false);assert.deepEqual(wait.coverage.correlationReasons,['pending']);
 const recent=await observer.recentCalls({callId:'wanted'},deadline());assert.deepEqual(recent.records,[]);assert.equal(recent.coverage.correlationComplete,true);assert.deepEqual(recent.coverage.correlationReasons,[]);
 ami.emit('Hangup','pending');const ended=await observer.recentCalls({callId:'wanted'},deadline());assert.equal(ended.coverage.correlationComplete,false);assert.deepEqual(ended.coverage.correlationReasons,['channel_gone']);
});
